### ISSUE TITLE
Typo on keymap description

### ISSUE THREAD

**Issue by Pheon-Dev** [desdic/macrothis.nvim#6]
{
    "desdic/macrothis.nvim",
    opts = {},
    keys = {
        { "<Leader>kks", function() require('macrothis').save() end, desc = "save register" },
        { "<Leader>kkl", function() require('macrothis').load() end, desc = "load register" }
        { "<Leader>kkd", function() require('macrothis').delete() end, desc = "delete register" } -- used load instead of delete
    }
},

**Comment by desdic** [comment]
Thanks its fixed now :)
